/* SPDX-License-Identifier: GPL-2.0 */
#ifndef PAGE_FLAGS_LAYOUT_H
#define PAGE_FLAGS_LAYOUT_H

/* DT test stubs for page-flags layout constants */
#ifndef NR_PAGEFLAGS
#define NR_PAGEFLAGS		26
#endif

#if defined(CONFIG_SPARSEMEM) && !defined(CONFIG_SPARSEMEM_VMEMMAP)
#define SECTIONS_WIDTH		SECTIONS_SHIFT  /* SECTIONS_WIDTH = SECTIONS_SHIFT */
#else
#define SECTIONS_WIDTH		0
#endif

#define ZONES_SHIFT 2
#define ZONES_WIDTH		ZONES_SHIFT

#if SECTIONS_WIDTH + ZONES_WIDTH + NODES_SHIFT <= BITS_PER_LONG - NR_PAGEFLAGS
#define NODES_WIDTH		NODES_SHIFT
#else
#ifdef CONFIG_SPARSEMEM_VMEMMAP
#error "[Depends] Vmemmap: No space for nodes field in page flags"
#endif
#define NODES_WIDTH		0
#endif

/* LAST_CPUPID field layout for DT test environment */
#ifdef CONFIG_NUMA_BALANCING

/* NR_CPUS_BITS: order_base_2(CONFIG_NR_CPUS). For CONFIG_NR_CPUS=4096, this is 12. */
#ifndef NR_CPUS_BITS
#define NR_CPUS_BITS	12
#endif

#define LAST__PID_SHIFT		8
#define LAST__PID_MASK		((1 << LAST__PID_SHIFT) - 1)
#define LAST__CPU_SHIFT		NR_CPUS_BITS
#define LAST__CPU_MASK		((1 << LAST__CPU_SHIFT) - 1)
#define LAST_CPUPID_SHIFT	(LAST__PID_SHIFT + LAST__CPU_SHIFT)

#if SECTIONS_WIDTH + ZONES_WIDTH + NODES_WIDTH + LAST_CPUPID_SHIFT <= BITS_PER_LONG - NR_PAGEFLAGS
#define LAST_CPUPID_WIDTH	LAST_CPUPID_SHIFT
#else
#define LAST_CPUPID_WIDTH	0
#endif

#if LAST_CPUPID_SHIFT != 0 && LAST_CPUPID_WIDTH == 0
#define LAST_CPUPID_NOT_IN_PAGE_FLAGS
#endif

#define LAST_CPUPID_PGOFF	(BITS_PER_LONG - SECTIONS_WIDTH - ZONES_WIDTH - \
				 NODES_WIDTH - LAST_CPUPID_SHIFT)
#define LAST_CPUPID_PGSHIFT	(LAST_CPUPID_PGOFF * (LAST_CPUPID_WIDTH != 0))
#define LAST_CPUPID_MASK	((1UL << LAST_CPUPID_SHIFT) - 1)
#endif /* CONFIG_NUMA_BALANCING */

#endif
